#!/bin/sh

flag_verbose='true'
flag_ssh='-i ec2backupkey'
flag_instance_type='--instance-type t1.micro --security-groups admin --key-name ec2key1'
image_id='ami-0ccb7d64' # for Ubuntu 14.04
directory=~/testdirectory

################## SETUP THE BACKUP INSTANCE ###################

# Determine kernel type of the local machine

# Create an instance with the same kernel type as the local machine
instance_id='aws ec2 run-instances $flag_instance_type --image-id image_id | grep INSTANCES | cut -f8' 

# Enter wait loop while instance is spooling
state=''
while [ "$state" != "running" ]  
do
	state='aws ec2 describe-instances --instance-id $instance_id | grep STATE | cut -f3'
done

# Determine the instance address for logging in
domain='aws ec2 describe-instances --instance-id $instance_id | grep ASSOCIATION | cut -f3 | awk 'NR==1{print $1}''

# Determine devices already mounted. Used later to determine our attached device.
existing_device="ssh '$flag_ssh' -o StrictHostKeyChecking=no ubuntu@'$domain' | grep 'xvd'"

# Attach volume to instance
device_id='/dev/sdx'
aws ec2 attach-volume --instance-id "$instance_id" --volume-id "$volume" --device "$deviceID"

# Enter wait loop while volume is attaching
state=''
while [ "$state" != "attached" ]  
do
	state='aws ec2 describe-volumes --volume-id "$volume" | grep ATTACHMENTS | cut -f6'
done
# Determine device name
backup_device="ssh '$flag_ssh' -o StrictHostKeyChecking=no ubuntu@'$domain' | ls /dev | grep 'xvd' | grep -v '$existing_device'"

# Format and Mount
ssh $flag_ssh -o StrictHostKeyChecking=no ubuntu@$domain sudo mkfs.ext4 /dev/$backup_device
mountPoint='/mnt/backup' #directory to mount backup volume
ssh $flag_ssh -o StrictHostKeyChecking=no ubuntu@$domain sudo mkdir $mountPoint # Create Mount point
ssh $flag_ssh -o StrictHostKeyChecking=no ubuntu@$domain sudo mount /dev/$backup_device $mountPoint

# Backup 
backup_timestamp='date +%d-%b-%H_%M' 
backup_directory='backup_'$backup_timestamp''
tar -zcvf $directory $backup_directory
dd if=$backup_directory | ssh $flag_ssh -o StrictHostKeyChecking=no ubuntu@$domain dd of=$mountPoint/$backup_directory
ssh $flag_ssh -o StrictHostKeyChecking=no ubuntu@$domain ls $mountPoint



################## BACKUP FILES ###################